[project]
name = "mixinv2-examples"
version = "0.1.0"
description = "Example case studies for MIXINv2"
license = "MIT"
requires-python = ">=3.13"
dependencies = ["mixinv2", "mixinv2-library"]

[tool.uv]
sources = { mixinv2 = { workspace = true }, mixinv2-library = { workspace = true } }
